-- 009: справочник понятий встаёт в очередь к человеку
--
-- Понятия завёл агент (миграция 008) — значит, и они черновики, пока человек
-- их не прочитал: определение «рудоконтролирующего фактора» решает, какие
-- связи признаков вообще имеют смысл, и цена ошибки здесь выше, чем в
-- отдельном паспорте.
--
-- Суррогатный номер нужен панели: её страницы адресуются числом
-- (/карточка/понятия/3), а первичный ключ справочника — текстовый код.
-- Код остаётся первичным ключом: на него ссылается bridge.feature_concept.

ALTER TABLE kb.concept
    ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE;

COMMENT ON COLUMN kb.concept.id IS
    'Номер для адресов панели; ссылаются на понятие по code, а не по нему';

-- Журнал решений должен принимать новый вид объекта.
ALTER TABLE meta.review DROP CONSTRAINT review_object_kind_check;
ALTER TABLE meta.review ADD CONSTRAINT review_object_kind_check
    CHECK (object_kind IN ('паспорт признака', 'паспорт слоя', 'лицензия',
                           'связь признак-понятие', 'понятие'));

-- Очередь на проверку: та же выборка плюс понятия.
CREATE OR REPLACE VIEW meta.confirmation_queue AS
    SELECT 'паспорт признака' AS вид, p.feature_id AS id, f.code AS код,
           p.status, p.model, p.updated_at AS изменён
      FROM meta.feature_passport p
      JOIN data.feature f ON f.id = p.feature_id
    UNION ALL
    SELECT 'паспорт слоя', p.layer_id, l.code, p.status, p.model, p.updated_at
      FROM meta.layer_passport p
      JOIN data.source_layer l ON l.id = p.layer_id
    UNION ALL
    SELECT 'лицензия', l.id, l.code, l.status, NULL, NULL
      FROM meta.license l
    UNION ALL
    SELECT 'связь признак-понятие', b.id, f.code || ' → ' || b.concept_code,
           b.status, r.model, NULL
      FROM bridge.feature_concept b
      JOIN data.feature f ON f.id = b.feature_id
      LEFT JOIN runs.run r ON r.id = b.run_id
    UNION ALL
    SELECT 'понятие', c.id, c.code, c.status, NULL, c.updated_at
      FROM kb.concept c;
